name: shopping_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.11.1+6
  cupertino_icons: ^0.1.2
  firebase_dynamic_links: ^0.4.0+2
  firebase_core: ^0.4.0+5
  shared_preferences: ^0.5.3+1
  cloud_firestore: ^0.12.5+1
  carousel_slider: ^1.3.0
  flutter_upi: ^0.0.2
  device_apps: ^1.0.8
  sensors: ^0.4.0+1
  url_launcher: ^5.1.2
  avatar_glow: 1.1.0
  intl: 0.16.1
  google_fonts: 0.3.8




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: 'assets/images/logo.png'
  android: true
  ios: true
  


flutter:

  uses-material-design: true

  

  assets:
    - assets/images/
