name: shopping_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.11.1+6
  google_sign_in: ^4.0.4
  cupertino_icons: ^0.1.2
  bmnav: ^0.3.4
  firebase_dynamic_links: ^0.4.0+2
  flushbar: ^1.8.2
  firebase_core: ^0.4.0+5
  country_pickers: ^1.0.1
  shared_preferences: ^0.5.3+1
  cloud_firestore: ^0.12.5+1
  carousel_slider: ^1.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  


flutter:

  uses-material-design: true

  

  assets:
    - assets/images/mountains.jpg
    - assets/images/logo_transparent.png
    - assets/images/default.png
    - assets/images/logo.png
    - assets/images/google_logo.png

